### ISSUE TITLE
Garage started incorrectly stating the open/close state after recent apt updates

### ISSUE THREAD

**Issue by RealDudePerson** [nathanpjones/GaragePi#20]
#### What's Wrong
Immediately after registering as open, the garage registers as closed again. This happens even as the garage is still open.
Note the timestamps in the data listed. This started happened after a recent update of system packages, but unfortunately I can't nail down a specific timeline. This setup has been otherwise working flawlessly for over a year, or since the last release update.

2022-05-12 14:52:17 | SensorTrip | Door state changed to CLOSED.
2022-05-12 14:52:16 | SensorTrip | Door state changed to OPEN.
2022-05-12 10:54:48 | SensorTrip | Door state changed to CLOSED.
2022-05-12 10:54:47 | SensorTrip | Door state changed to OPEN.
2022-05-12 10:53:03 | SensorTrip | Door state changed to CLOSED.
2022-05-12 10:53:02 | SensorTrip | Door state changed to OPEN.
2022-05-11 17:05:39 | SensorTrip | Door state changed to CLOSED.
2022-05-11 17:05:38 | SensorTrip | Door state changed to OPEN.

#### Environment Info

**RPi Model**:
raspberry pi zero w

**OS Release**:
Raspbian GNU/Linux 10 (buster)

**Service Status**:

N/A

#### Attach Logs

The only notable log.

2022-05-10 19:21:25,414 [359  :0xb6f20900] CONTROL ERROR Exception while running controller [in app @ /home/pi/GaragePi/backend/app.py:113]
Traceback (most recent call last):
  File "/home/pi/GaragePi/backend/app.py", line 111, in main
    GaragePiController(config['IPC_PORT']).start()
  File "/home/pi/GaragePi/backend/controller.py", line 50, in start
    msg = socket.recv_multipart()
  File "/home/pi/GaragePi/venv/lib/python3.7/site-packages/zmq/sugar/socket.py", line 566, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 783, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 819, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
  File "/home/pi/GaragePi/backend/app.py", line 99, in sigterm_handler
    sys.exit(0)
SystemExit: 0

**Comment by RealDudePerson** [comment]
Replaced pi, reflashed os, soldered new cable, and none of that worked.

Replaced the magnetic switch and resolved the issue.
